akka {
  actor {
    provider = "cluster"

    serializers {
      custom-bin = "domain.serialization.AkkaSerializerAdapter"
    }

    serialization-bindings {
        "domain.network.Model" = custom-bin
        "actors.gossip.GossipProtocol$GossipCommand$HandleRemoteModel" = custom-bin
        "actors.gossip.dataset_distribution.DatasetDistributionProtocol$HandleDistributeDataset" = custom-bin
        "actors.gossip.GossipProtocol$ControlCommand" = custom-bin
        "actors.gossip.configuration.ConfigurationProtocol$RequestInitialConfig" = custom-bin
        "actors.gossip.configuration.ConfigurationProtocol$ShareConfig" = custom-bin
        "actors.gossip.configuration.ConfigurationProtocol$RequestInitialConfig" = custom-bin
        "actors.gossip.consensus.ConsensusProtocol$RequestModelForConsensus" = custom-bin
        "actors.gossip.consensus.ConsensusProtocol$ConsensusModelReply" = custom-bin
        "actors.authentication.AuthProtocol$Register" = custom-bin
        "actors.authentication.AuthProtocol$RegisterReply" = custom-bin
        "actors.authentication.AuthProtocol$Authenticate" = custom-bin
        "actors.authentication.AuthProtocol$AuthenticateReply" = custom-bin
        "actors.authentication.AuthProtocol$ValidateToken" = custom-bin
        "actors.authentication.AuthProtocol$ValidateTokenReply" = custom-bin
    }

    allow-java-serialization = off
  }

  remote.artery {
    canonical.hostname = "127.0.0.1"
    canonical.port = 5082
  }

  cluster {
    run-coordinated-shutdown-when-down = off
    seed-nodes = [
      "akka://ClusterSystem@127.0.0.1:5082"
    ]

    timers {
      unreachable-node = 120s
      seed-unreachable-timeout = 20s
      join-timeout = 15s
      bootstrap-check = 15s
    }
  }
}
